name: 'Create Build configuration for App Center'
description: 'This action creates a build configuration from the existing branch config for App Center CI'
inputs:
  appcenter-token:
    description: 'Value of your App Center token'
    required: true
  project-id:
    description: 'Name of your project ({{org/project_name}})'
    required: true
  source-branch:
    description: 'Name of your source branch name (cloneFromBranch)'
    required: true
  target-branch:
    description: 'Name of your target branch ({{current_branch}})'
    required: true
runs:
  using: 'node12'
  main: 'index.js'